/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TopicInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subtopics' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const Topic = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subtopics' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTopic' : IDL.Func([TopicInput], [IDL.Nat], []),
  'deleteTopic' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getTopic' : IDL.Func([IDL.Nat], [Topic], ['query']),
  'getTopicsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
  'seedSampleData' : IDL.Func([], [], []),
  'updateTopic' : IDL.Func([IDL.Nat, TopicInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TopicInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subtopics' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const Topic = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subtopics' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addTopic' : IDL.Func([TopicInput], [IDL.Nat], []),
    'deleteTopic' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getTopic' : IDL.Func([IDL.Nat], [Topic], ['query']),
    'getTopicsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Topic)], ['query']),
    'seedSampleData' : IDL.Func([], [], []),
    'updateTopic' : IDL.Func([IDL.Nat, TopicInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };